apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews3-deploy
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews3
        image: europe-west8-docker.pkg.dev/tesi-federico-siano-istio/tesi-repo/review3-module:latest
        ports:
        - containerPort: 8100