apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews1-deploy
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews1
        image: europe-west8-docker.pkg.dev/tesi-federico-siano-istio/tesi-repo/review1-module:latest
        ports:
        - containerPort: 8100